  # Power Management Configuration for Archinstaller
# Defines which power management daemon to use based on CPU

intel:
  modern:  # 6th gen+ with kernel 6.0+
    daemon: power-profiles-daemon
    description: "Modern Intel with P-State support"
  legacy:  # Older CPUs or kernel
    daemon: tuned-ppd
    description: "Older Intel CPUs"
  budget:  # Atom, Celeron, Pentium
    daemon: tuned-ppd
    description: "Budget Intel CPUs"

amd:
  modern:  # Ryzen 5000+ with kernel 6.0+
    daemon: power-profiles-daemon
    description: "Modern Ryzen with P-State"
  legacy:  # Ryzen 1000-4000
    daemon: tuned-ppd
    description: "Older Ryzen (1st-4th gen)"

default:
  daemon: tuned-ppd
  description: "Safe default for unknown CPUs"

# Available profiles
profiles:
  tuned:
    powersave: "Maximum battery life"
    balanced: "Balance performance and battery"
    performance: "Maximum CPU performance"

  power-profiles-daemon:
    power-saver: "Maximize battery life"
    balanced: "Default balanced mode"
    performance: "Maximum performance"
