#!/bin/bash
set -uo pipefail

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# Use different variable names to avoid conflicts
INSTALLED=()
ENABLED=()
CONFIGURED=()

# ======= Fail2ban Setup Steps =======
install_fail2ban() {
  if pacman -Q fail2ban >/dev/null 2>&1; then
    log_info "fail2ban already installed, skipping"
    return 0
  fi
  
  ui_info "Installing fail2ban..."
  if pacman_install_single "fail2ban" false; then
    INSTALLED+=("fail2ban")
    return 0
  else
    return 1
  fi
}

# Pick the ban action matching the firewall the installer set up.
# UFW  -> banaction = ufw (ships with fail2ban, integrates with ufw rules)
# firewalld -> banaction = firewallcmd-allports
# neither -> iptables-multiport (fail2ban default)
pick_banaction() {
  if [ "${FIREWALL_PREFERENCE:-ufw}" = "firewalld" ] && systemctl list-unit-files firewalld.service &>/dev/null; then
    echo "firewallcmd-allports"
  elif command -v ufw >/dev/null 2>&1; then
    echo "ufw"
  else
    echo "iptables-multiport"
  fi
}

configure_fail2ban() {
  local jail_local="/etc/fail2ban/jail.local"
  local jail_dropin="/etc/fail2ban/jail.d/archinstaller.local"

  # Prefer a dedicated drop-in: it survives package updates of jail.conf,
  # never collides with an existing user jail.local, and is read last so it wins.
  if [ -f "$jail_dropin" ]; then
    log_info "archinstaller fail2ban drop-in already exists, skipping configuration"
    CONFIGURED+=("jail.d/archinstaller.local")
    return 0
  fi

  # Migrate legacy state: old installer versions copied the full jail.conf to
  # jail.local WITHOUT enabling any jail — fail2ban ran while protecting nothing.
  # That file is just a copy of the stock jail.conf, so replace it wholesale.
  if [ -f "$jail_local" ] && ! grep -qE '^\s*enabled\s*=\s*true' "$jail_local"; then
    if diff -q /etc/fail2ban/jail.conf "$jail_local" >/dev/null 2>&1 || \
       ! grep -q 'Generated by archinstaller' "$jail_local" 2>/dev/null; then
      local backup="${jail_local}.backup.$(date +%Y%m%d_%H%M%S)"
      sudo cp "$jail_local" "$backup"
      sudo rm "$jail_local"
      log_warning "Replaced legacy jail.local (no jails enabled) — backup at $backup"
    fi
  fi

  local banaction
  banaction=$(pick_banaction)

  ui_info "Configuring fail2ban (sshd jail, banaction: $banaction)..."
  sudo tee "$jail_dropin" >/dev/null <<EOF
# Generated by archinstaller
[DEFAULT]
backend = systemd
bantime = 1h
findtime = 10m
maxretry = 3
banaction = $banaction

[sshd]
enabled = true
# aggressive mode catches more brute-force variants
filter = sshd[mode=aggressive]
EOF

  # Validate config before restarting — a broken jail config would stop fail2ban from starting
  if command -v fail2ban-client >/dev/null 2>&1; then
    if ! sudo fail2ban-client -t >>"$INSTALL_LOG" 2>&1; then
      log_error "fail2ban config validation failed — check $INSTALL_LOG. Removing generated drop-in."
      sudo rm -f "$jail_dropin"
      return 1
    fi
    log_success "fail2ban config validated"
  fi

  log_success "fail2ban configured (sshd jail enabled, banaction: $banaction)"
  CONFIGURED+=("jail.d/archinstaller.local")
}

enable_and_start_fail2ban() {
  ui_info "Enabling and starting fail2ban service..."
  if sudo systemctl enable --now fail2ban >>"$INSTALL_LOG" 2>&1; then
    log_success "fail2ban service enabled and started"
    ENABLED+=("fail2ban")
    return 0
  else
    log_error "Failed to enable and start fail2ban service"
    return 1
  fi
}

status_fail2ban() {
  if sudo systemctl status fail2ban --no-pager >>"$INSTALL_LOG" 2>&1; then
    log_success "fail2ban service is running"
    return 0
  else
    log_error "fail2ban service is not running"
    return 1
  fi
}

# Verify the sshd jail is actually loaded and banning-capable
verify_jails() {
  if ! command -v fail2ban-client >/dev/null 2>&1; then
    log_warning "fail2ban-client not available for verification"
    return 0
  fi

  sleep 2  # give the daemon a moment after start/reload
  local jail_status
  jail_status=$(sudo fail2ban-client status 2>>"$INSTALL_LOG") || {
    log_error "Could not query fail2ban status"
    return 1
  }

  if echo "$jail_status" | grep -qw sshd; then
    local banned_total
    banned_total=$(sudo fail2ban-client status sshd 2>>"$INSTALL_LOG" | grep -i 'currently banned' | grep -o '[0-9]*')
    log_success "sshd jail is active and monitoring (currently banned IPs: ${banned_total:-0})"
    return 0
  else
    log_error "sshd jail is NOT active! Check: sudo fail2ban-client status"
    return 1
  fi
}

# ======= Main =======
main() {
  echo -e "${THEME_BORDER}=== Fail2ban Setup ===${RESET}"

  run_step "Installing fail2ban" install_fail2ban
  # Configure BEFORE starting so the service comes up with jails active,
  # then reload to pick up the config in case the service was already running
  run_step "Configuring fail2ban (sshd jail)" configure_fail2ban
  run_step "Enabling and starting fail2ban" enable_and_start_fail2ban
  sudo systemctl reload fail2ban >>"$INSTALL_LOG" 2>&1 || true
  run_step "Verifying sshd jail is active" verify_jails
  run_step "Checking fail2ban status" status_fail2ban
}

main "$@"
